
- name: Debug core variables
  debug: msg={{ item }}
  with_items:
  - "{{ partition }}"
  - "{{ java_iface }}"
  tags:
  - sc

- name: Fail if java_iface missing
  fail: msg="java_iface missing"
  when: java_iface is not defined
  register: java_iface_check
  ignore_errors: True
  tags:
  - walrus

- name: Debug return values
  debug: msg="{{ item }}"
  with_items:
  - "{{ java_iface_check }}"
  tags:
  - walrus
  - debug
